---
version: "3.8"

services:
  db:
    image: postgres:13.5
    restart: always
    environment:
      POSTGRES_USER: comentar
      POSTGRES_PASSWORD: comentar
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ppt@ppt.pt
      PGADMIN_DEFAULT_PASSWORD: ppt
    ports:
      - "5050:80"
    depends_on:
      - db

  dev:
    image: politica-para-todos/comentar:latest
    build: .
    environment:
      - BINDING=0.0.0.0
      - POSTGRES_USER=comentar
      - POSTGRES_PASSWORD=comentar
      - POSTGRES_HOST=db
      - RAILS_ENV=development
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app:cached
    depends_on:
      - db
    command:
      - sleep
      - infinity

volumes:
  postgres-data:
