export default [
    "Nuno Carneiro",
    "Rui Gonçalves",
    "Hugo Barroca",
    "Inês Rosete",
    "Ana Neves",
    "Tiago Sousa",
    "Vasco Patarata",
    "Renato Almeida",
    "Miguel Spranger",
    "Paulo Fonseca",
    "Luís Silva",
    "Nuno Cruz",
    "João Gonçalves",
]
